apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-deployment
  namespace: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense
  template:
    metadata:
      labels:
        app: expense
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z mongo-service 27017; do echo waiting for mongo; sleep 2; done;']
      containers:
        - name: expense-container
          image: rakshitsen/expense:9
          ports:
            - containerPort: 3000
          # env:
          #   - name: PORT
          #     value: "3000"
          #   - name: MONGO_URL
          #     value: "mongodb://mongo:27017"
          #   - name: DB_NAME
          #     value: "project"
          #   - name: COLLECTION_NAME
          #     value: "expense"
          envFrom:
            - configMapRef:
                name: expense-config
