apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volumes
spec:
  storageClassName: standard 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/db/data"
