version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - expense
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    image: rakshitsen/expense:8
    container_name: expense
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - expense

volumes:
  mongo_data:

networks:
  expense:
